#!/usr/bin/env python3
"""Stage 15.9 bounded MuJoCo injection of Stage 15.6 J^T f candidate torques.

This replaces the deterministic Stage 15.8 smoke waveform with actual J^T f
candidate torques generated by the Stage 15.6 Pinocchio candidate chain.
It remains a short-horizon low-alpha smoke test, not stable locomotion.
"""

from __future__ import annotations

import argparse
import csv
import importlib.util
import json
import math
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import numpy as np

try:
    import mujoco
except Exception as exc:  # pragma: no cover
    mujoco = None  # type: ignore[assignment]
    MUJOCO_IMPORT_ERROR = f"{type(exc).__name__}: {exc}"
else:
    MUJOCO_IMPORT_ERROR = ""

LEGS = ("FR", "FL", "RR", "RL")
JOINT_KINDS = ("hip", "thigh", "calf")
SMOKE_STEPS = 200
AUDIT_CTRL_LIMIT = 0.25
TARGET_MAX_CTRL = 0.18


def load_json(path: Path) -> Dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def load_stage15_6_module(repo_root: Path):
    path = repo_root / "scripts/stage15_6_real_model_jacobian_candidate_rollout.py"
    spec = importlib.util.spec_from_file_location("stage15_6_real_model_jacobian_candidate_rollout", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load Stage 15.6 module: {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def resolve_repo_path(repo_root: Path, rel_or_abs: str) -> Path:
    path = Path(rel_or_abs)
    if path.is_absolute():
        return path
    return (repo_root / path).resolve()


def initial_state(model, data) -> None:
    data.qpos[:] = 0.0
    data.qvel[:] = 0.0
    if getattr(model, "nkey", 0) > 0:
        data.qpos[:] = np.asarray(model.key_qpos[0]).reshape(-1)[: model.nq]
    else:
        for jid in range(model.njnt):
            if int(model.jnt_type[jid]) == int(mujoco.mjtJoint.mjJNT_FREE):
                adr = int(model.jnt_qposadr[jid])
                if adr + 7 <= model.nq:
                    data.qpos[adr + 0] = 0.0
                    data.qpos[adr + 1] = 0.0
                    data.qpos[adr + 2] = 0.32
                    data.qpos[adr + 3] = 1.0
                    data.qpos[adr + 4] = 0.0
                    data.qpos[adr + 5] = 0.0
                    data.qpos[adr + 6] = 0.0
                break
    if model.nu:
        data.ctrl[:] = 0.0
    mujoco.mj_forward(model, data)


def actuator_ctrl_limits(model, aid: int) -> Tuple[float, float]:
    lower, upper = -AUDIT_CTRL_LIMIT, AUDIT_CTRL_LIMIT
    try:
        if bool(model.actuator_ctrllimited[aid]):
            cr = model.actuator_ctrlrange[aid]
            lower = max(lower, float(cr[0]))
            upper = min(upper, float(cr[1]))
    except Exception:
        pass
    if lower > upper:
        lower, upper = -AUDIT_CTRL_LIMIT, AUDIT_CTRL_LIMIT
    return lower, upper


def actuator_mapping_from_stage15_7(stage15_7: Dict[str, Any]) -> List[Dict[str, Any]]:
    matched_actuators = stage15_7.get("matched_actuators") or []
    mapping = []
    for item in matched_actuators:
        if not item.get("matched"):
            continue
        aid = int(item.get("actuator_id", -1))
        order = int(item.get("candidate_order", -1))
        if aid >= 0 and 0 <= order < 12:
            mapping.append(
                {
                    "candidate_order": order,
                    "actuator_id": aid,
                    "actuator_name": item.get("actuator_name", ""),
                    "joint_name": item.get("matched_joint_name", ""),
                }
            )
    mapping = sorted(mapping, key=lambda x: (x["candidate_order"], x["actuator_id"]))
    seen = set()
    out = []
    for item in mapping:
        if item["actuator_id"] in seen:
            continue
        seen.add(item["actuator_id"])
        out.append(item)
    return out


def build_stage15_6_context(repo_root: Path, stage15_5_report_path: Path):
    m = load_stage15_6_module(repo_root)
    report = m.load_json(stage15_5_report_path)
    loaded = m.load_pinocchio_model_from_stage15_5(report, repo_root)
    return m, report, loaded


def pinocchio_tau_candidate_12(stage15_6_module, loaded: Dict[str, Any], step: int) -> Tuple[np.ndarray, Dict[str, Any]]:
    model = loaded["model"]
    data = loaded["data"]
    joint_map = loaded["joint_map"]
    foot_map = loaded["foot_map"]
    contacts = stage15_6_module.phase_contacts(step)
    accel = stage15_6_module.desired_base_accel(step)
    forces = stage15_6_module.contact_forces(mass=12.0, gravity=9.81, accel=accel, contacts=contacts)
    q = stage15_6_module.q_for_step(model, joint_map, step)
    tau = np.zeros(model.nv)
    jacobian_norms: List[float] = []
    for leg in LEGS:
        if not contacts[leg]:
            continue
        frame_name = foot_map[leg]
        Jv = stage15_6_module.frame_jacobian_linear(model, data, q, frame_name)
        jacobian_norms.append(float(np.linalg.norm(Jv)))
        tau += Jv.T @ forces[leg]

    tau12: List[float] = []
    missing_names: List[str] = []
    for leg in LEGS:
        for kind in JOINT_KINDS:
            jname = (joint_map.get(leg) or {}).get(kind, "")
            value = None
            if jname:
                try:
                    jid = model.getJointId(jname)
                    if 0 < jid < len(model.names):
                        idx = int(model.idx_vs[jid])
                        nvj = int(model.nvs[jid])
                        if nvj >= 1 and idx < tau.size:
                            value = float(tau[idx])
                except Exception:
                    value = None
            if value is None:
                missing_names.append(jname)
                idx_fallback = len(tau12)
                value = float(tau[idx_fallback]) if idx_fallback < tau.size else 0.0
            tau12.append(value)
    meta = {
        "contacts": contacts,
        "desired_accel": accel.tolist(),
        "jacobian_norm_min": float(min(jacobian_norms)) if jacobian_norms else 0.0,
        "jacobian_norm_max": float(max(jacobian_norms)) if jacobian_norms else 0.0,
        "missing_pinocchio_joint_names": missing_names,
    }
    return np.asarray(tau12, dtype=float), meta


def estimate_safe_alphas(stage15_6_summary: Dict[str, Any]) -> List[float]:
    max_tau = float(stage15_6_summary.get("max_tau_candidate_abs", 0.0))
    if not np.isfinite(max_tau) or max_tau <= 1e-9:
        max_tau = 100.0
    alpha_max = min(0.001, TARGET_MAX_CTRL / max_tau)
    alpha_max = max(alpha_max, 1e-6)
    return [0.0, alpha_max * 0.25, alpha_max * 0.50, alpha_max]


def run_one_alpha(model, alpha: float, actuator_map: List[Dict[str, Any]], stage15_6_module, loaded: Dict[str, Any], steps: int) -> Tuple[Dict[str, Any], List[Dict[str, Any]]]:
    data = mujoco.MjData(model)
    initial_state(model, data)
    rows: List[Dict[str, Any]] = []
    nonfinite_steps = 0
    nonzero_ctrl_steps = 0
    saturation_steps = 0
    max_abs_ctrl = 0.0
    max_abs_tau12 = 0.0
    max_abs_qvel = 0.0
    min_base_z = float("inf")
    jacobian_norm_min = float("inf")
    jacobian_norm_max = 0.0
    missing_name_count_max = 0

    for step in range(steps):
        tau12, meta = pinocchio_tau_candidate_12(stage15_6_module, loaded, step)
        max_abs_tau12 = max(max_abs_tau12, float(np.max(np.abs(tau12))) if tau12.size else 0.0)
        if meta["jacobian_norm_min"] > 0.0:
            jacobian_norm_min = min(jacobian_norm_min, meta["jacobian_norm_min"])
        jacobian_norm_max = max(jacobian_norm_max, meta["jacobian_norm_max"])
        missing_name_count_max = max(missing_name_count_max, len(meta["missing_pinocchio_joint_names"]))

        if model.nu:
            data.ctrl[:] = 0.0
        step_saturated = False
        for item in actuator_map:
            aid = int(item["actuator_id"])
            order = int(item["candidate_order"])
            if aid < 0 or aid >= model.nu or order < 0 or order >= tau12.size:
                continue
            raw = float(alpha * tau12[order])
            lower, upper = actuator_ctrl_limits(model, aid)
            clipped = float(np.clip(raw, lower, upper))
            if abs(clipped - raw) > 1e-12:
                step_saturated = True
            data.ctrl[aid] = clipped
        ctrl_max = float(np.max(np.abs(data.ctrl))) if model.nu else 0.0
        max_abs_ctrl = max(max_abs_ctrl, ctrl_max)
        if ctrl_max > 1e-12:
            nonzero_ctrl_steps += 1
        if step_saturated:
            saturation_steps += 1
        mujoco.mj_step(model, data)
        if not (np.all(np.isfinite(data.qpos)) and np.all(np.isfinite(data.qvel))):
            nonfinite_steps += 1
        max_abs_qvel = max(max_abs_qvel, float(np.max(np.abs(data.qvel))) if model.nv else 0.0)
        base_z = float(data.qpos[2]) if model.nq >= 3 else 0.0
        min_base_z = min(min_base_z, base_z)
        if step % 10 == 0 or step == steps - 1:
            rows.append(
                {
                    "alpha": alpha,
                    "step": step,
                    "tau12_max_abs": float(np.max(np.abs(tau12))) if tau12.size else 0.0,
                    "ctrl_max_abs": ctrl_max,
                    "jacobian_norm_min": meta["jacobian_norm_min"],
                    "jacobian_norm_max": meta["jacobian_norm_max"],
                    "qpos_finite": int(bool(np.all(np.isfinite(data.qpos)))),
                    "qvel_finite": int(bool(np.all(np.isfinite(data.qvel)))),
                    "base_z": base_z,
                    "qvel_max_abs": float(np.max(np.abs(data.qvel))) if model.nv else 0.0,
                    "ncon": int(data.ncon),
                }
            )
    if jacobian_norm_min == float("inf"):
        jacobian_norm_min = 0.0
    summary = {
        "alpha": alpha,
        "steps": steps,
        "nonzero_ctrl_steps": int(nonzero_ctrl_steps),
        "nonfinite_steps": int(nonfinite_steps),
        "saturation_steps": int(saturation_steps),
        "max_abs_ctrl": float(max_abs_ctrl),
        "max_abs_tau12": float(max_abs_tau12),
        "max_abs_qvel": float(max_abs_qvel),
        "min_base_z": float(min_base_z),
        "jacobian_norm_min": float(jacobian_norm_min),
        "jacobian_norm_max": float(jacobian_norm_max),
        "missing_pinocchio_joint_name_count_max": int(missing_name_count_max),
    }
    return summary, rows


def run_injection(repo_root: Path, stage15_5_path: Path, stage15_6_summary_path: Path, stage15_7_path: Path, output_csv: Path, output_json: Path) -> Dict[str, Any]:
    if mujoco is None:
        raise RuntimeError(f"MuJoCo import failed: {MUJOCO_IMPORT_ERROR}")
    stage15_6_summary = load_json(stage15_6_summary_path)
    stage15_7 = load_json(stage15_7_path)
    mjcf_model_path = resolve_repo_path(repo_root, stage15_7.get("mjcf_model_path", ""))
    if not mjcf_model_path.exists():
        raise RuntimeError(f"missing MJCF model path from Stage 15.7: {mjcf_model_path}")
    model = mujoco.MjModel.from_xml_path(str(mjcf_model_path))
    actuator_map = actuator_mapping_from_stage15_7(stage15_7)
    stage15_6_module, _report, loaded = build_stage15_6_context(repo_root, stage15_5_path)
    alphas = estimate_safe_alphas(stage15_6_summary)

    all_rows: List[Dict[str, Any]] = []
    alpha_summaries: List[Dict[str, Any]] = []
    for alpha in alphas:
        summary, rows = run_one_alpha(model, alpha, actuator_map, stage15_6_module, loaded, SMOKE_STEPS)
        alpha_summaries.append(summary)
        all_rows.extend(rows)

    output_csv.parent.mkdir(parents=True, exist_ok=True)
    with output_csv.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "alpha", "step", "tau12_max_abs", "ctrl_max_abs", "jacobian_norm_min", "jacobian_norm_max",
                "qpos_finite", "qvel_finite", "base_z", "qvel_max_abs", "ncon",
            ],
        )
        writer.writeheader()
        writer.writerows(all_rows)

    total_nonzero = sum(s["nonzero_ctrl_steps"] for s in alpha_summaries if s["alpha"] > 0.0)
    total_nonfinite = sum(s["nonfinite_steps"] for s in alpha_summaries)
    total_saturation = sum(s["saturation_steps"] for s in alpha_summaries)
    max_ctrl = max((s["max_abs_ctrl"] for s in alpha_summaries), default=0.0)
    max_tau12 = max((s["max_abs_tau12"] for s in alpha_summaries), default=0.0)
    jac_min = min((s["jacobian_norm_min"] for s in alpha_summaries if s["jacobian_norm_min"] > 0.0), default=0.0)
    jac_max = max((s["jacobian_norm_max"] for s in alpha_summaries), default=0.0)
    missing_joint_count_max = max((s["missing_pinocchio_joint_name_count_max"] for s in alpha_summaries), default=0)

    summary = {
        "stage": "15.9",
        "name": "mujoco_jtf_candidate_injection",
        "mujoco_imported": mujoco is not None,
        "mujoco_import_error": MUJOCO_IMPORT_ERROR,
        "mujoco_model_loaded": True,
        "mjcf_model_path": str(mjcf_model_path.relative_to(repo_root)) if mjcf_model_path.is_relative_to(repo_root) else str(mjcf_model_path),
        "stage15_6_jtf_candidate_used": True,
        "deterministic_smoke_waveform_used": False,
        "pinocchio_model_source": loaded.get("model_source", ""),
        "real_geometry_loaded": bool(loaded.get("real_geometry_loaded", False)),
        "nq": int(model.nq),
        "nv": int(model.nv),
        "nu": int(model.nu),
        "mapped_actuator_count": int(len(actuator_map)),
        "actuator_map": actuator_map,
        "alphas": alphas,
        "steps_per_alpha": SMOKE_STEPS,
        "audit_ctrl_limit": AUDIT_CTRL_LIMIT,
        "target_max_ctrl": TARGET_MAX_CTRL,
        "total_nonzero_ctrl_steps_positive_alpha": int(total_nonzero),
        "total_nonfinite_steps": int(total_nonfinite),
        "total_saturation_steps": int(total_saturation),
        "max_abs_ctrl": float(max_ctrl),
        "max_abs_tau12": float(max_tau12),
        "jacobian_norm_min": float(jac_min),
        "jacobian_norm_max": float(jac_max),
        "missing_pinocchio_joint_name_count_max": int(missing_joint_count_max),
        "mj_step_called": True,
        "stable_locomotion_claimed": False,
        "short_horizon_jtf_injection_only": True,
        "alpha_summaries": alpha_summaries,
        "boundary": {
            "mujoco_jtf_candidate_injection_used": True,
            "ros_publisher_used": False,
            "frozen_mixed_baseline_modified": False,
            "torque_enable_ready_claimed": False,
            "hardware_deployment_claimed": False,
            "stable_locomotion_claimed": False,
            "short_horizon_only": True,
        },
        "notes": [
            "This stage injects Stage 15.6 J^T f candidate torques, not the Stage 15.8 deterministic waveform.",
            "Alphas are automatically bounded from Stage 15.6 max candidate torque and a target max command.",
            "This remains a short-horizon smoke test, not stable locomotion validation.",
        ],
    }
    output_json.write_text(json.dumps(summary, indent=2, ensure_ascii=False), encoding="utf-8")
    return summary


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--stage15-5-report", type=Path, default=None)
    parser.add_argument("--stage15-6-summary", type=Path, default=None)
    parser.add_argument("--stage15-7-summary", type=Path, default=None)
    parser.add_argument("--output-csv", type=Path, default=None)
    parser.add_argument("--output-json", type=Path, default=None)
    args = parser.parse_args(argv)

    repo_root = args.repo_root.resolve()
    log_dir = repo_root / "results/logs_sample"
    stage15_5_path = args.stage15_5_report or log_dir / "stage15_5_model_readiness_audit.json"
    stage15_6_path = args.stage15_6_summary or log_dir / "stage15_6_real_model_jacobian_candidate_rollout_summary.json"
    stage15_7_path = args.stage15_7_summary or log_dir / "stage15_7_mujoco_candidate_compatibility_audit_summary.json"
    output_csv = args.output_csv or log_dir / "stage15_9_mujoco_jtf_candidate_injection.csv"
    output_json = args.output_json or log_dir / "stage15_9_mujoco_jtf_candidate_injection_summary.json"

    summary = run_injection(repo_root, stage15_5_path, stage15_6_path, stage15_7_path, output_csv, output_json)
    print("stage15_9_injection_completed: true")
    print(f"mjcf_model_path: {summary['mjcf_model_path']}")
    print(f"mapped_actuator_count: {summary['mapped_actuator_count']}")
    print(f"pinocchio_model_source: {summary['pinocchio_model_source']}")
    print(f"real_geometry_loaded: {summary['real_geometry_loaded']}")
    print(f"alphas: {summary['alphas']}")
    print(f"total_nonzero_ctrl_steps_positive_alpha: {summary['total_nonzero_ctrl_steps_positive_alpha']}")
    print(f"total_nonfinite_steps: {summary['total_nonfinite_steps']}")
    print(f"total_saturation_steps: {summary['total_saturation_steps']}")
    print(f"max_abs_ctrl: {summary['max_abs_ctrl']}")
    print(f"max_abs_tau12: {summary['max_abs_tau12']}")
    print(f"output_json: {output_json}")
    print(f"output_csv: {output_csv}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
